# Generated by Django 4.1 on 2023-08-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name='Имя/Название',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField()),
                (
                    'singer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='music.singer',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('track_number_in_album', models.PositiveIntegerField()),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='music.album',
                    ),
                ),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='music.song',
                    ),
                ),
            ],
            options={
                'unique_together': {('album', 'song')},
            },
        ),
    ]
