# Generated by Django 4.1 on 2023-08-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_albumsong_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('track_number_in_album', 'song', 'album')},
        ),
    ]
